allowBuilds:
  '@firebase/util': set this to true or false
  '@nestjs/core': false
  '@scarf/scarf': false
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: set this to true or false
  unrs-resolver: false
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - bcrypt
  - msgpackr-extract
  - unrs-resolver
packages:
  - mock-inverter-server
  - regression-tests
